### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [danijar/dreamer#1]
Hi, 

first of all amazing work. Would it be possible to properly comment/format the code in order to increase readability/understandability? So, for example, noobs like me can better follow what it is going on :)

Thank you

Cheers,

Francesco

**Comment by danijar** [comment]
Hi Francesco, thanks for your comment. Feel free to fork the repository and format it in the way that works best for you. Comments are quite minimal by design, to avoid clutter and keep the code fast to edit --- I like this style for research code. If you haven't read the paper yet, I recommend doing that to understand the algorithm. Afterwards, I think the code should be easy to understand.
