### ISSUE TITLE
Image_loss, Model_loss logged as inf

### ISSUE THREAD

**Issue by yuqingd** [danijar/dreamer#10]
Hi,

When running dreamer.py with the dm_control reacher environments, we are finding that the image_loss and model_loss are consistently logged as infs. Are there changes that need to be made for this particular environment to avoid this issue?

(Screenshot of outputs when running with debug parameters)
![image](https://user-images.githubusercontent.com/14207005/77598314-b2c02580-6ebe-11ea-9e9e-d97139c360fb.png)

Thanks!

**Comment by danijar** [comment]
This is expected when training with mixed precision. You could try training with `--precision 32` to see if that solves the problem. You can also check out the docs on the [LossScaleOptimizer](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/experimental/LossScaleOptimizer) for more details on why this happens when training with mixed precision.

**Comment by yuqingd** [comment]
Thank you, this was really helpful!
