### ISSUE TITLE
How to train on low-dimensional Gym envs?

### ISSUE THREAD

**Issue by jarlva** [danijar/dreamer#16]
Hi,

I have a custom env, derived from Gym classic_control/cartpole (but more difficult to solve). I currently use OpenAI stable baseline's ACKTR to train. I'd like to switch to dreamer but I read that it's pixel/Atari focused. Cartpole is not. Can dreamer be used (maybe little modified) for that?

**Comment by danijar** [comment]
Thanks for your question. We have run PlaNet on low-dim inputs in the past and it worked well. The changes we made were to swap the encoder and decoder from conv layers to dense layers and to train more frequently. I think the same would work for Dreamer:

- Change `ConvEncoder` in models.py to look at the proprioceptive keys instead and use dense layers, e.g. 4 hidden layers of size 400.
- Change `ConvDecoder` in models.py in a similar way to predict a distribution over low-dim inputs.
- Change [this line](https://github.com/danijar/dreamer/blob/1e38b1d80e11335883108720e671d35cc34de96e/dreamer.py#L165) in dreamer.py to compute the log-prob of the low-dim data instead of the image.
- Comment out the image summaries because we're not predicting images anymore.

The code is already quite fast so I would try this first. When it works, you can also disable rendering in the environment to further speed things up and save RAM in the replay buffer. You can also try changing `--train_every` to, say, 200.
