### ISSUE TITLE
Why actor-critic loss is weighted by accumulated discount?

### ISSUE THREAD

**Issue by IcarusWizard** [danijar/dreamer#18]
Hi Danijar. I have a question about the actor-critic loss.  

In line 192 and 198, the loss is given by lambda returns weighted by accumulated discount.  In the paper, it is said that 'terms are weighted down based on how likely the imagined trajectory would have ended'. I am confused by this intuition. I know in terminal state, the value of next state should be weighted by 0 like in DQN. But this behavior is already involved in the computation of lambda returns since the bellman backups multiply pcont in every steps. And the weighted loss is also used in no-episodic dmc tasks, which have no terminal state. So why we need this additional weight?

Could it be viewed as a variance reduction technique? The imagined  trajectory will accumulate error through time, so it is better to put smaller weight on states with higher time steps since they are less reliable.

**Comment by danijar** [comment]
It accounts for the distribution of states the agent would visit in the environment. If it visits a state less often, it should spend less model capacity on maximizing the value of that state. More importantly, if a state is never visited, because we're asking the model to predict beyond the episode end, we shouldn't train on that state at all because the model output could be anything in that case. That comes from maximizing the expected value under the policy. In a model-free agent, you sample states from the replay buffer so they already approximately follow the stationary distribution of the agent.
